import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, doc, getDocs, getDoc, addDoc, deleteDoc, query, where, orderBy, serverTimestamp, runTransaction } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig, emailConfig } from './firebase-config.js';

import { DEFAULT_TUTORIALS } from './tutorial-data.js';
const CATS={android:'أندرويد',windows:'ويندوز',kali:'لينكس وكالي',web:'تطوير الويب',troubleshoot:'حلول المشاكل'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let app,auth,db,user=null,tutorials=[...DEFAULT_TUTORIALS],likes=new Set(),currentArticle=null;
const ready=()=>firebaseConfig.apiKey!=='YOUR_FIREBASE_API_KEY'&&firebaseConfig.projectId!=='YOUR_PROJECT_ID';
function notice(message){let n=$('#siteNotice');if(!n){n=document.createElement('div');n.id='siteNotice';n.className='site-notice';document.body.append(n);}n.textContent=message;}
async function initFirebase(){if(!ready()){notice('قاعدة البيانات غير مهيأة بعد. أضف إعدادات Firebase في firebase-config.js.');return false;}app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);try{if(!auth.currentUser)await signInAnonymously(auth);user=auth.currentUser;return true;}catch(e){console.error(e);notice('تعذر الاتصال بخدمات Firebase. راجع إعدادات Authentication.');return false;}}
async function loadTutorials(){if(!db)return;try{const snap=await getDocs(collection(db,'tutorials'));if(!snap.empty){tutorials=snap.docs.map(d=>({id:d.id,...d.data()}));}const likeSnap=await getDocs(collection(db,'likes'));const counts=new Map();likeSnap.docs.forEach(d=>{const articleId=String(d.data().articleId);counts.set(articleId,(counts.get(articleId)||0)+1);});tutorials=tutorials.map(t=>({...t,likes:counts.get(String(t.id))||0}));renderCards();}catch(e){console.error(e);notice('تعذر تحميل الشروحات من قاعدة البيانات.');}}
function likesFor(id){return likes.has(String(id))?1:0;}
async function loadMyLikes(articleId){if(!db||!user)return false;const ref=doc(db,'likes',`${articleId}_${user.uid}`);const snap=await getDoc(ref);return snap.exists();}
function renderCards(){const queryText=$('#searchInput').value.trim().toLowerCase();const active=document.querySelector('.filter-btn.active')?.dataset.filter||'all';const list=tutorials.filter(t=>(active==='all'||t.category===active)&&`${t.title} ${t.desc} ${CATS[t.category]||''}`.toLowerCase().includes(queryText));$('#tutorialGrid').innerHTML=list.map(t=>`<a class="tutorial-card" href="/article/${encodeURIComponent(t.id)}"><div class="card-image"><img src="${esc(t.imageUrl||'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1000')}" alt="${esc(t.title)}" loading="lazy"><span class="card-category">${esc(CATS[t.category]||'دليل تقني')}</span></div><div class="card-body"><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><div class="card-meta"><span>♥ ${Number(t.likes)||0} إعجاب</span><span class="read-more">اقرأ الشرح ←</span></div></div></a>`).join('');$('#emptyState').hidden=list.length>0;}
function setFilter(f){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderCards();}
function normalizeVideo(url){if(!url)return '';try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return `https://www.youtube.com/embed/${u.pathname.slice(1)}`;if(u.hostname.includes('youtube.com')&&u.pathname==='/watch')return `https://www.youtube.com/embed/${u.searchParams.get('v')}`;return url;}catch{return '';}}
async function openArticle(id){const t=tutorials.find(x=>String(x.id)===String(id));if(!t)return;currentArticle=t;let liked=false,commentRows=[];if(db&&user){try{liked=await loadMyLikes(id);const q=query(collection(db,'comments'),where('articleId','==',String(id)),orderBy('createdAt','desc'));const s=await getDocs(q);commentRows=s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.error(e);}}
const paragraphs=String(t.articleContent||'').split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('');const video=normalizeVideo(t.videoUrl);const comments=commentRows.map(c=>`<div class="comment"><b>${esc(c.author||'زائر')}</b><p>${esc(c.body)}</p><small>${c.createdAt?.toDate?c.createdAt.toDate().toLocaleString('ar-IQ'):''}</small></div>`).join('');
$('#articleContent').innerHTML=`<header class="article-head"><span class="section-kicker">${esc(CATS[t.category]||'دليل تقني')}</span><h1>${esc(t.title)}</h1><p>${esc(t.desc)}</p></header>${t.imageUrl?`<img class="article-cover" src="${esc(t.imageUrl)}" alt="${esc(t.title)}">`:''}<div class="article-text">${paragraphs}${t.code?`<div class="code-box"><div><b>${esc(t.codeLabel||'CODE')}</b><button id="copyCode" type="button">نسخ الكود</button></div><pre><code>${esc(t.code)}</code></pre></div>`:''}${t.extra?`<p>${esc(t.extra)}</p>`:''}</div>${t.downloadUrl?`<p><a class="btn btn-primary" href="${esc(t.downloadUrl)}" target="_blank" rel="noopener">تحميل الملفات والموارد ↗</a></p>`:''}${video?`<h3>شاهد الشرح بالفيديو</h3><iframe class="article-video" src="${esc(video)}" title="${esc(t.title)}" loading="lazy" allowfullscreen></iframe>`:''}<div class="article-actions"><button class="article-action ${liked?'liked':''}" id="likeArticle">♥ <span>${Number(t.likes)||0}</span> إعجاب</button><button class="article-action" id="shareArticle">مشاركة الشرح ↗</button></div><section class="article-comments"><h3>التعليقات <span>(${commentRows.length})</span></h3><form class="comment-form" id="commentForm"><input name="author" maxlength="45" placeholder="اسمك الكريم" required><textarea name="body" rows="3" maxlength="1000" placeholder="اكتب تعليقك أو سؤالك..." required></textarea><button class="btn btn-primary" type="submit">إرسال التعليق</button></form><div id="commentsList">${comments||'<p class="muted">كن أول من يترك تعليقاً.</p>'}</div></section>`;
$('#articleModal').classList.add('open');$('#articleModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
$('#copyCode')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(t.code);$('#copyCode').textContent='تم النسخ ✓';});
$('#shareArticle').addEventListener('click',async()=>{const url=`${location.href.split('#')[0]}#article-${t.id}`;if(navigator.share)await navigator.share({title:t.title,url});else{await navigator.clipboard.writeText(url);$('#shareArticle').textContent='تم نسخ الرابط ✓';}});
$('#likeArticle').addEventListener('click',()=>toggleLike(t));$('#commentForm').addEventListener('submit',e=>{e.preventDefault();submitComment(t.id,e.currentTarget);});}
async function toggleLike(t){if(!db||!user){alert('خدمة الإعجابات غير مهيأة حالياً.');return;}const id=String(t.id),ref=doc(db,'likes',`${id}_${user.uid}`),btn=$('#likeArticle');btn.disabled=true;try{let likedNow=false;await runTransaction(db,async tx=>{const s=await tx.get(ref);if(s.exists())tx.delete(ref);else{tx.set(ref,{articleId:id,userId:user.uid,createdAt:serverTimestamp()});likedNow=true;}});const q=await getDocs(query(collection(db,'likes'),where('articleId','==',id)));t.likes=q.size;$('#likeArticle span').textContent=String(q.size);btn.classList.toggle('liked',likedNow);renderCards();}catch(e){console.error(e);alert('تعذر حفظ الإعجاب. حاول مرة أخرى.');}finally{btn.disabled=false;}}
async function submitComment(articleId,form){if(!db||!user){alert('التعليقات غير متاحة حتى تكتمل إعدادات قاعدة البيانات.');return;}const fd=new FormData(form),author=String(fd.get('author')||'').trim(),body=String(fd.get('body')||'').trim(),button=form.querySelector('button');if(!author||!body)return;button.disabled=true;button.textContent='جارٍ الإرسال…';try{const banned=await getDoc(doc(db,'bannedUsers',user.uid));if(banned.exists()){alert('هذا الحساب غير مسموح له بإضافة التعليقات.');return;}await addDoc(collection(db,'comments'),{articleId:String(articleId),author,body,userId:user.uid,createdAt:serverTimestamp()});form.reset();await openArticle(articleId);}catch(e){console.error(e);alert('تعذر نشر التعليق. حاول مرة أخرى.');}finally{button.disabled=false;button.textContent='إرسال التعليق';}}
function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');document.body.style.overflow='';if(id==='#articleModal'&&location.hash.startsWith('#article-'))history.replaceState(null,'',location.pathname+location.search);}
function initTheme(){if(localStorage.getItem('hadoorTheme')==='dark')document.body.classList.add('dark');$('#themeToggle').textContent=document.body.classList.contains('dark')?'☀':'☾';$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');localStorage.setItem('hadoorTheme',dark?'dark':'light');$('#themeToggle').textContent=dark?'☀':'☾';});}
function initContact(){const open=()=>{$('#contactModal').classList.add('open');$('#contactModal').setAttribute('aria-hidden','false');};$('#openContact').addEventListener('click',open);$('#closeContact').addEventListener('click',()=>closeModal('#contactModal'));$('[data-close-contact]').addEventListener('click',()=>closeModal('#contactModal'));$('#contactForm').addEventListener('submit',async e=>{e.preventDefault();const status=$('#contactStatus'),button=e.currentTarget.querySelector('button');if(!emailConfig.configured||emailConfig.publicKey.startsWith('YOUR_')){status.textContent='نموذج البريد يحتاج إعداد EmailJS في firebase-config.js أولاً.';return;}button.disabled=true;status.textContent='جارٍ إرسال رسالتك…';try{emailjs.init({publicKey:emailConfig.publicKey});await emailjs.sendForm(emailConfig.serviceId,emailConfig.templateId,e.currentTarget);e.currentTarget.reset();status.textContent='وصلت رسالتك بنجاح، شكراً لتواصلك معنا.';}catch(err){console.error(err);status.textContent='لم نتمكن من إرسال الرسالة. حاول لاحقاً.';}finally{button.disabled=false;}});}
function init(){initTheme();$('#year').textContent=new Date().getFullYear();$('#menuToggle').addEventListener('click',()=>{const open=$('#mainNav').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open));});document.querySelectorAll('#mainNav a').forEach(a=>a.addEventListener('click',()=>$('#mainNav').classList.remove('open')));$('#filterList').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b)setFilter(b.dataset.filter);});document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{setFilter(b.dataset.category);location.hash='tutorials';}));$('#searchInput').addEventListener('input',renderCards);initContact();renderCards();}
init();
const firebaseReady=await initFirebase();if(firebaseReady){await loadTutorials();const likeDocs=await getDocs(query(collection(db,'likes'),where('userId','==',user.uid)));likes=new Set(likeDocs.docs.map(d=>d.data().articleId));}
