import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, getDocs, addDoc, setDoc, deleteDoc, query, orderBy, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const configured=firebaseConfig.apiKey!=='YOUR_FIREBASE_API_KEY'&&firebaseConfig.projectId!=='YOUR_PROJECT_ID';let app,auth,db,adminUser=null;
if(configured){app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);}else $('#loginStatus').textContent='أضف إعدادات Firebase في firebase-config.js أولاً.';
$('#googleLogin').addEventListener('click',async()=>{if(!configured)return;$('#loginStatus').textContent='جارٍ فتح تسجيل Google…';try{const provider=new GoogleAuthProvider();await signInWithPopup(auth,provider);}catch(e){console.error(e);$('#loginStatus').textContent='تعذر تسجيل الدخول: '+e.message;}});
if(auth)onAuthStateChanged(auth,async user=>{if(!user){adminUser=null;$('#loginPanel').hidden=false;$('#dashboard').hidden=true;return;}try{const adminDoc=await getDoc(doc(db,'admins',user.uid));if(!adminDoc.exists()){await signOut(auth);$('#loginStatus').textContent='هذا الحساب غير مخوّل لإدارة الموقع. أضف UID الخاص بك إلى مجموعة admins في Firestore.';return;}adminUser=user;$('#loginPanel').hidden=true;$('#dashboard').hidden=false;$('#adminEmail').textContent=user.email||'';await loadArticles();await loadComments();}catch(e){console.error(e);$('#loginStatus').textContent='تعذر التحقق من صلاحيات المشرف.';}});
$('#logout').addEventListener('click',()=>signOut(auth));
function switchTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#articlesPanel').hidden=tab!=='articles';$('#commentsPanel').hidden=tab!=='comments';}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));

$('#importStarter').addEventListener('click',async()=>{if(!confirm('سيتم استيراد مقالات البداية إلى قاعدة البيانات. متابعة؟'))return;try{const response=await fetch('./starter-tutorials.json');if(!response.ok)throw new Error('starter file missing');const rows=await response.json();for(const row of rows){const {id,...data}=row;await setDoc(doc(db,'tutorials',String(id)),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),updatedBy:adminUser.uid},{merge:true});}alert('تم استيراد مقالات البداية.');await loadArticles();}catch(err){console.error(err);alert('تعذر استيراد المقالات.');}});
$('#newArticle').addEventListener('click',()=>{const f=$('#articleForm');f.reset();f.elements.id.value='';f.hidden=false;f.scrollIntoView({behavior:'smooth'});});$('#cancelEdit').addEventListener('click',()=>$('#articleForm').hidden=true);
async function loadArticles(){const snap=await getDocs(query(collection(db,'tutorials'),orderBy('updatedAt','desc')));$('#adminArticles').innerHTML=snap.empty?'<p class="muted">لا توجد مقالات منشورة في قاعدة البيانات. أضف أول شرح من الزر أعلاه.</p>':snap.docs.map(d=>{const x=d.data();return `<article class="admin-list-item"><div><b>${esc(x.title)}</b><small>${esc(x.category||'')}</small></div><div class="admin-row-actions"><button class="filter-btn" data-edit="${esc(d.id)}">تعديل</button><button class="filter-btn danger" data-delete="${esc(d.id)}">حذف</button></div></article>`;}).join('');}
$('#adminArticles').addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const snap=await getDoc(doc(db,'tutorials',edit.dataset.edit));if(!snap.exists())return;const x=snap.data(),f=$('#articleForm');for(const k of ['id','title','category','imageUrl','desc','articleContent','code','codeLabel','extra','videoUrl','downloadUrl'])f.elements[k].value=k==='id'?snap.id:(x[k]||'');f.hidden=false;f.scrollIntoView({behavior:'smooth'});}if(del&&confirm('هل أنت متأكد من حذف هذا الشرح؟')){await deleteDoc(doc(db,'tutorials',del.dataset.delete));await loadArticles();}});
$('#articleForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=String(fd.get('id')||'').trim(),data={title:String(fd.get('title')).trim(),category:fd.get('category'),imageUrl:String(fd.get('imageUrl')).trim(),desc:String(fd.get('desc')).trim(),articleContent:String(fd.get('articleContent')).trim(),code:String(fd.get('code')).trim(),codeLabel:String(fd.get('codeLabel')).trim(),extra:String(fd.get('extra')).trim(),videoUrl:String(fd.get('videoUrl')).trim(),downloadUrl:String(fd.get('downloadUrl')).trim(),updatedAt:serverTimestamp(),updatedBy:adminUser.uid};const status=$('#articleStatus');try{if(id)await setDoc(doc(db,'tutorials',id),data,{merge:true});else await addDoc(collection(db,'tutorials'),{...data,createdAt:serverTimestamp(),likes:0});f.hidden=true;f.reset();status.textContent='تم حفظ المقال بنجاح.';await loadArticles();}catch(err){console.error(err);status.textContent='تعذر حفظ المقال. تحقق من قواعد Firestore.';}});
async function loadComments(){const snap=await getDocs(query(collection(db,'comments'),orderBy('createdAt','desc')));$('#adminComments').innerHTML=snap.empty?'<p class="muted">لا توجد تعليقات.</p>':snap.docs.map(d=>{const c=d.data();return `<article class="admin-list-item comment-admin"><div><b>${esc(c.author||'زائر')}</b><p>${esc(c.body||'')}</p><small>المقال: ${esc(c.articleId||'')} · UID: ${esc(c.userId||'')}</small></div><div class="admin-row-actions"><button class="filter-btn danger" data-comment-delete="${esc(d.id)}">حذف</button><button class="filter-btn danger" data-ban="${esc(c.userId||'')}" ${!c.userId?'disabled':''}>حظر</button></div></article>`;}).join('');}
$('#adminComments').addEventListener('click',async e=>{const del=e.target.closest('[data-comment-delete]'),ban=e.target.closest('[data-ban]');try{if(del&&confirm('حذف هذا التعليق؟')){await deleteDoc(doc(db,'comments',del.dataset.commentDelete));await loadComments();}if(ban&&ban.dataset.ban&&confirm('حظر هذا الحساب من التعليق؟')){await setDoc(doc(db,'bannedUsers',ban.dataset.ban),{uid:ban.dataset.ban,bannedAt:serverTimestamp(),bannedBy:adminUser.uid});await loadComments();}}catch(err){console.error(err);alert('تعذر تنفيذ العملية.');}});
$('#refreshComments').addEventListener('click',loadComments);
